[project]
name = "poc"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "httpx[http2]==0.28.1",
    "lxml>=6.0.1",
    "pandas>=2.3.2",
    "tqdm>=4.67.1",
]
